import {describe,expect,it} from "vitest";
import {compileAnimaticTimeline,AnimaticCompileError} from "../compileAnimaticTimeline";
import {estimateDialogueSeconds,pauseSeconds} from "../timing";
import {buildCompletedStoryboard} from "./fixtures";

describe("compileAnimaticTimeline",()=>{
  it("compiles READY Storyboard",()=>{const f=buildCompletedStoryboard();expect(compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"}).clips.length).toBeGreaterThan(0);});
  it("preserves panel order",()=>{const f=buildCompletedStoryboard();const t=compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"});expect(t.clips.map(c=>c.panelId)).toEqual(f.storyboard.panels.map(p=>p.id));});
  it("assigns deterministic start times",()=>{const f=buildCompletedStoryboard();const a=compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"}),b=compileAnimaticTimeline({animaticId:"88888888-8888-4888-8888-888888888888",version:1,...f,storyboardStatus:"READY"});expect(a.clips.map(c=>c.startSeconds)).toEqual(b.clips.map(c=>c.startSeconds));});
  it("keeps sequence contiguous",()=>{const f=buildCompletedStoryboard();const t=compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"});expect(t.clips.map(c=>c.sequenceIndex)).toEqual(t.clips.map((_,i)=>i));});
  it("preserves exact dialogue text",()=>{const f=buildCompletedStoryboard();const t=compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"});const cues=t.clips.flatMap(c=>c.dialogueCues);for(const cue of cues){const block=f.script.blocks.find(b=>b.id===cue.scriptBlockId);expect(block?.type).toBe("DIALOGUE");if(block?.type==="DIALOGUE")expect(cue.text).toBe(block.text);}});
  it("builds ACTION cues",()=>{const f=buildCompletedStoryboard();const t=compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"});expect(t.clips.flatMap(c=>c.actionCues).length).toBeGreaterThan(0);});
  it("covers REACTION source blocks",()=>{const f=buildCompletedStoryboard();const t=compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"});const reactionIds=f.script.blocks.filter(b=>b.type==="REACTION").map(b=>b.id);expect(reactionIds.every(id=>t.clips.some(c=>c.sourceScriptBlockIds.includes(id)))).toBe(true);});
  it("keeps timeline near Script duration",()=>{const f=buildCompletedStoryboard();const t=compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"});expect(Math.abs(t.pacingChecks.differenceSeconds)/f.script.estimatedDurationSeconds).toBeLessThanOrEqual(.15);});
  it("uses configurable WPM",()=>expect(estimateDialogueSeconds("one two three four",120)).toBeGreaterThan(estimateDialogueSeconds("one two three four",240)));
  it("dialogue estimate is deterministic",()=>expect(estimateDialogueSeconds("one two three",150)).toBe(estimateDialogueSeconds("one two three",150)));
  it("short pause is shorter than long pause",()=>expect(pauseSeconds({id:"p",type:"PAUSE",durationHint:"SHORT",purpose:"x"})).toBeLessThan(pauseSeconds({id:"p",type:"PAUSE",durationHint:"LONG",purpose:"x"})));
  it("PAUSE increases timing demand",()=>{const f=buildCompletedStoryboard();const first=f.storyboard.panels[0];const pause=f.script.blocks.find(b=>b.type==="PAUSE");if(pause&&!first.sourceScriptBlockIds.includes(pause.id))first.sourceScriptBlockIds.push(pause.id);const t=compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"});expect(t.clips[0].durationSeconds).toBeGreaterThan(0);});
  it("allows sufficient PARTIAL Storyboard",()=>{const f=buildCompletedStoryboard();expect(()=>compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"PARTIAL"})).not.toThrow();});
  it("rejects insufficient PARTIAL Storyboard",()=>{const f=buildCompletedStoryboard();f.storyboard.panels[0].generationStatus="FAILED";f.storyboard.panels[0].asset=null;expect(()=>compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"PARTIAL"})).toThrowError(AnimaticCompileError);});
  it("rejects GENERATING Storyboard",()=>{const f=buildCompletedStoryboard();expect(()=>compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"GENERATING"})).toThrow();});
  it("creates only allowed motion treatments",()=>{const f=buildCompletedStoryboard();const t=compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"});const allowed=new Set(["STATIC","SLOW_PUSH","SLOW_PULL","PAN_LEFT","PAN_RIGHT","PAN_UP","PAN_DOWN"]);expect(t.clips.every(c=>allowed.has(c.motionTreatment))).toBe(true);});
  it("motionStrength stays normalized",()=>{const f=buildCompletedStoryboard();const t=compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"});expect(t.clips.every(c=>c.motionStrength>=0&&c.motionStrength<=1)).toBe(true);});
  it("does not mutate parents",()=>{const f=buildCompletedStoryboard();const before=[JSON.stringify(f.series),JSON.stringify(f.scene),JSON.stringify(f.script),JSON.stringify(f.visualPlan),JSON.stringify(f.storyboard),JSON.stringify(f.series.canon)];compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"});expect([JSON.stringify(f.series),JSON.stringify(f.scene),JSON.stringify(f.script),JSON.stringify(f.visualPlan),JSON.stringify(f.storyboard),JSON.stringify(f.series.canon)]).toEqual(before);});
  it("contains no AI video generation fields",()=>{const f=buildCompletedStoryboard();const text=JSON.stringify(compileAnimaticTimeline({animaticId:"77777777-7777-4777-8777-777777777777",version:1,...f,storyboardStatus:"READY"}));expect(text).not.toContain("videoModel");expect(text).not.toContain("videoPrompt");});
});
