import {NextRequest} from "next/server";
import {beforeEach,describe,expect,it,vi} from "vitest";
vi.mock("@/lib/supabase/server",()=>({createServerSupabaseClient:vi.fn()}));
vi.mock("@/lib/supabase/admin",()=>({createAdminSupabaseClient:vi.fn()}));
vi.mock("@/lib/series/persistence/getSeries",()=>({getSeries:vi.fn()}));
vi.mock("@/lib/scenes/persistence/getScene",()=>({getScene:vi.fn()}));
vi.mock("@/lib/scripts/persistence/getScript",()=>({getScript:vi.fn()}));
vi.mock("@/lib/visual-planning/persistence/getVisualPlan",()=>({getVisualPlan:vi.fn()}));
vi.mock("@/lib/storyboards/persistence",async()=>{const actual=await vi.importActual<any>("@/lib/storyboards/persistence");return{...actual,getLatestStoryboard:vi.fn(),getPanelStates:vi.fn()};});
import {createServerSupabaseClient} from "@/lib/supabase/server";
import {createAdminSupabaseClient} from "@/lib/supabase/admin";
import {getSeries} from "@/lib/series/persistence/getSeries";
import {getScene} from "@/lib/scenes/persistence/getScene";
import {getScript} from "@/lib/scripts/persistence/getScript";
import {getVisualPlan} from "@/lib/visual-planning/persistence/getVisualPlan";
import {getLatestStoryboard,getPanelStates} from "@/lib/storyboards/persistence";
import {theWoundsWeKeep} from "@/lib/series/demoBlueprint";
import {buildValidScene} from "@/lib/scenes/__tests__/fixtures";
import {buildValidScript} from "@/lib/scripts/__tests__/fixtures";
import {buildValidVisualPlan} from "@/lib/visual-planning/__tests__/fixtures";
import {POST} from "../generate/route";
const ids={seriesId:"22222222-2222-4222-8222-222222222222",sceneId:"11111111-1111-4111-8111-111111111111",scriptId:"33333333-3333-4333-8333-333333333333",planId:"55555555-5555-4555-8555-555555555555"};
const req=(body:any={mode:"INITIAL"})=>new NextRequest("http://x",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
const userClient=(id:string|null)=>({auth:{getUser:async()=>({data:{user:id?{id}:null},error:null})}}) as any;
const adminClient=(result:any={data:true,error:null})=>({rpc:vi.fn(async()=>result)}) as any;

beforeEach(()=>{
 vi.resetAllMocks();
 vi.mocked(createServerSupabaseClient).mockResolvedValue(userClient("u"));
 vi.mocked(createAdminSupabaseClient).mockReturnValue(adminClient());
 vi.mocked(getSeries).mockResolvedValue({blueprint:theWoundsWeKeep} as any);
 vi.mocked(getScene).mockResolvedValue({blueprint:buildValidScene()} as any);
 vi.mocked(getScript).mockResolvedValue({script:buildValidScript()} as any);
 vi.mocked(getVisualPlan).mockResolvedValue({plan:buildValidVisualPlan()} as any);
 vi.mocked(getLatestStoryboard).mockResolvedValue(null);
 vi.mocked(getPanelStates).mockResolvedValue([]);
});
describe("POST storyboard generation",()=>{
 it("returns 401 unauthenticated",async()=>{vi.mocked(createServerSupabaseClient).mockResolvedValue(userClient(null));expect((await POST(req(),{params:Promise.resolve(ids)})).status).toBe(401);});
 it("rejects extra request fields",async()=>expect((await POST(req({mode:"INITIAL",creatorId:"x"}),{params:Promise.resolve(ids)})).status).toBe(400));
 it("returns 404 for invalid parent IDs",async()=>expect((await POST(req(),{params:Promise.resolve({...ids,planId:"bad"})})).status).toBe(404));
 it("returns 404 for foreign parent chain",async()=>{vi.mocked(getSeries).mockRejectedValue(new Error("missing"));expect((await POST(req(),{params:Promise.resolve(ids)})).status).toBe(404);});
 it("returns existing READY storyboard as 200",async()=>{vi.mocked(getLatestStoryboard).mockResolvedValue({id:"66666666-6666-4666-8666-666666666666",status:"READY",blueprint:{panels:[{}]}} as any);expect((await POST(req(),{params:Promise.resolve(ids)})).status).toBe(200);});
 it("returns existing GENERATING storyboard as 202",async()=>{vi.mocked(getLatestStoryboard).mockResolvedValue({id:"66666666-6666-4666-8666-666666666666",status:"GENERATING",blueprint:{panels:[{}]}} as any);expect((await POST(req(),{params:Promise.resolve(ids)})).status).toBe(202);});
 it("returns 202 only after service-role atomic RPC succeeds",async()=>expect((await POST(req(),{params:Promise.resolve(ids)})).status).toBe(202));
 it("request route never invokes an image provider",async()=>{await POST(req(),{params:Promise.resolve(ids)});expect(JSON.stringify(vi.mocked(createAdminSupabaseClient).mock.calls)).not.toContain("images.generate");});
 it("returns 503 if atomic durable queue transaction fails",async()=>{vi.mocked(createAdminSupabaseClient).mockReturnValue(adminClient({data:null,error:{code:"X"}}));expect((await POST(req(),{params:Promise.resolve(ids)})).status).toBe(503);});
 it("reloads race winner if atomic RPC reports duplicate",async()=>{vi.mocked(createAdminSupabaseClient).mockReturnValue(adminClient({data:false,error:null}));vi.mocked(getLatestStoryboard).mockResolvedValueOnce(null).mockResolvedValueOnce({id:"66666666-6666-4666-8666-666666666666",status:"GENERATING",blueprint:{panels:[{},{}]}} as any);expect((await POST(req(),{params:Promise.resolve(ids)})).status).toBe(202);});
});
