import {fireEvent,render,screen} from "@testing-library/react";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {buildValidSound} from "@/lib/sound-design/__tests__/fixtures";
import {buildEpisodeMixTimeline} from "@/lib/sound-design/mix";
import type {SoundCueState} from "@/lib/sound-design/types";
import {EpisodeSoundWorkspace} from "./EpisodeSoundWorkspace";

function ready(){
 const f=buildValidSound(),dialogue=structuredClone(f.plan),plan=structuredClone(f.soundPlan);
 dialogue.lines.forEach((l,i)=>{l.generationStatus="COMPLETED";l.audioAsset={url:"https://example.com/dialogue-"+i+".wav",storagePath:"d-"+i+".wav",mimeType:"audio/wav",durationSeconds:l.visualWindowSeconds,sampleRate:24000,channels:1};});
 const states:SoundCueState[]=plan.cues.filter(c=>c.type!=="SILENCE").map((c,i)=>({cueId:c.id,status:"COMPLETED" as const,asset:{url:"https://example.com/sound-"+i+".mp3",storagePath:"s-"+i+".mp3",mimeType:"audio/mpeg" as const,durationSeconds:c.type==="AMBIENCE"&&c.loopable?Math.min(30,c.durationSeconds):c.durationSeconds,durationSource:"REQUESTED" as const,loopable:c.type==="AMBIENCE"&&c.loopable},errorCode:null,retryCount:0}));
 const mix=buildEpisodeMixTimeline({episode:f.episodeTimeline,dialogue,plan,states});
 return{...f,dialogue,plan,states,mix};
}
describe("EpisodeSoundWorkspace",()=>{
 beforeEach(()=>{vi.spyOn(HTMLMediaElement.prototype,"play").mockResolvedValue();vi.spyOn(HTMLMediaElement.prototype,"pause").mockImplementation(()=>{});});
 afterEach(()=>vi.restoreAllMocks());
 it("renders Sound Workspace",()=>{const f=ready();render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);expect(screen.getByText("Episode Sound")).toBeInTheDocument();});
 it("renders four track labels",()=>{const f=ready();render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);for(const x of ["Dialogue","Music","Ambience","Effects"])expect(screen.getByText(x)).toBeInTheDocument();});
 it("plays Episode",()=>{const f=ready();render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);fireEvent.click(screen.getByRole("button",{name:"Play Episode"}));expect(screen.getByRole("button",{name:"Pause"})).toBeInTheDocument();});
 it("mutes Dialogue",()=>{const f=ready();render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);fireEvent.click(screen.getByRole("button",{name:"Mute Dialogue"}));expect(screen.getByRole("button",{name:"Unmute Dialogue"})).toBeInTheDocument();});
 it("mutes Music",()=>{const f=ready();render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);fireEvent.click(screen.getByRole("button",{name:"Mute Music"}));expect(screen.getByRole("button",{name:"Unmute Music"})).toBeInTheDocument();});
 it("mutes Ambience",()=>{const f=ready();render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);fireEvent.click(screen.getByRole("button",{name:"Mute Ambience"}));expect(screen.getByRole("button",{name:"Unmute Ambience"})).toBeInTheDocument();});
 it("mutes Effects",()=>{const f=ready();render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);fireEvent.click(screen.getByRole("button",{name:"Mute Effects"}));expect(screen.getByRole("button",{name:"Unmute Effects"})).toBeInTheDocument();});
 it("seeks on global timeline",()=>{const f=ready();render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);fireEvent.change(screen.getByLabelText("Sound episode scrubber"),{target:{value:1}});expect((screen.getByLabelText("Sound episode scrubber") as HTMLInputElement).value).toBe("1");});
 it("shows cue status",()=>{const f=ready();render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);expect(screen.getAllByText("Ready").length).toBeGreaterThan(0);});
 it("shows intentional silence",()=>{const f=ready();render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);expect(screen.getByText("Intentional silence")).toBeInTheDocument();});
 it("shows editorial warning",()=>{const f=ready();f.plan.validation.warnings=["SFX cue overlaps dialogue at high priority."];render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);expect(screen.getByText(/overlaps dialogue/)).toBeInTheDocument();});
 it("renders retry for failed cue",()=>{const f=ready();f.states[0]={...f.states[0],status:"FAILED",asset:null,errorCode:"INTERNAL_TRANSIENT"};render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="PARTIAL" statusEndpoint="/s" retryBase="/s"/>);expect(screen.getByRole("button",{name:"Retry cue"})).toBeInTheDocument();});
 it("keeps Mix & Master disabled",()=>{const f=ready();render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);expect(screen.getByRole("button",{name:"Mix & Master"})).toBeDisabled();});
 it("hides provider internals",()=>{const f=ready();const{container}=render(<EpisodeSoundWorkspace timeline={f.episodeTimeline} dialogue={f.dialogue} initialPlan={f.plan} initialStates={f.states} initialMix={f.mix} initialStatus="READY" statusEndpoint="/s" retryBase="/s"/>);expect(container.textContent).not.toMatch(/claim_token|lease_expires_at|ELEVENLABS_API_KEY/);});
});
