import {describe,expect,it} from "vitest";
import {compileEpisodeTimeline,EpisodeAssemblyError} from "../compileEpisodeTimeline";
import {buildReadyEpisodeSources,buildValidEpisodeTimeline} from "./fixtures";

function compile(status:any="READY"){
  const f=buildReadyEpisodeSources();
  return compileEpisodeTimeline({
    assemblyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",seriesId:f.motionPlan.seriesId,episodeKey:"episodeOne",version:1,
    scenes:[{order:0,motionPlanStatus:status,series:f.series,scene:f.scene,script:f.script,visualPlan:f.visualPlan,storyboard:f.storyboard,animatic:f.timeline,motionPlan:f.motionPlan}]
  });
}

describe("Episode Assembly compiler",()=>{
 it("compiles READY MotionPlan",()=>expect(compile().scenes).toHaveLength(1));
 it.each(["PARTIAL","FAILED","GENERATING"] as const)("rejects %s MotionPlan",status=>expect(()=>compile(status)).toThrowError(EpisodeAssemblyError));
 it("preserves Animatic order",()=>{const f=buildValidEpisodeTimeline();expect(f.episodeTimeline.scenes[0].clips.map(c=>c.sourceAnimaticClipId)).toEqual(f.timeline.clips.map(c=>c.id));});
 it("preserves target durations",()=>{const f=buildValidEpisodeTimeline();expect(f.episodeTimeline.scenes[0].clips.map(c=>c.durationSeconds)).toEqual(f.timeline.clips.map(c=>c.durationSeconds));});
 it("uses completed Motion video",()=>{const f=buildValidEpisodeTimeline();const i=f.motionPlan.clips.findIndex(c=>c.generationStatus==="COMPLETED");expect(f.episodeTimeline.scenes[0].clips[i].mediaType).toBe("MOTION_VIDEO");expect(f.episodeTimeline.scenes[0].clips[i].asset.url).toBe(f.motionPlan.clips[i].outputAsset!.url);});
 it("uses Storyboard still for SKIPPED",()=>{const f=buildReadyEpisodeSources();f.motionPlan.clips[0].generationStatus="SKIPPED";f.motionPlan.clips[0].outputAsset=null;const t=compileEpisodeTimeline({assemblyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",seriesId:f.motionPlan.seriesId,episodeKey:"episodeOne",version:1,scenes:[{order:0,motionPlanStatus:"READY",series:f.series,scene:f.scene,script:f.script,visualPlan:f.visualPlan,storyboard:f.storyboard,animatic:f.timeline,motionPlan:f.motionPlan}]});expect(t.scenes[0].clips[0].mediaType).toBe("STILL_HOLD");expect(t.scenes[0].clips[0].asset.url).toBe(f.motionPlan.clips[0].inputAsset.url);});
 it("logically trims longer provider video",()=>{const f=buildValidEpisodeTimeline();const c=f.episodeTimeline.scenes[0].clips.find(x=>x.mediaType==="MOTION_VIDEO")!;expect(c.asset.sourceDurationSeconds).toBeGreaterThanOrEqual(c.durationSeconds);expect(c.sourceOffsetSeconds).toBe(0);});
 it("never changes source asset",()=>{const f=buildReadyEpisodeSources();const before=JSON.stringify(f.motionPlan);compileEpisodeTimeline({assemblyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",seriesId:f.motionPlan.seriesId,episodeKey:"episodeOne",version:1,scenes:[{order:0,motionPlanStatus:"READY",series:f.series,scene:f.scene,script:f.script,visualPlan:f.visualPlan,storyboard:f.storyboard,animatic:f.timeline,motionPlan:f.motionPlan}]});expect(JSON.stringify(f.motionPlan)).toBe(before);});
 it("preserves Script traceability",()=>{const f=buildValidEpisodeTimeline();expect(f.episodeTimeline.scenes[0].clips.map(c=>c.sourceScriptBlockIds)).toEqual(f.timeline.clips.map(c=>c.sourceScriptBlockIds));});
 it("preserves VisualBeat traceability",()=>{const f=buildValidEpisodeTimeline();expect(f.episodeTimeline.scenes[0].clips.map(c=>c.sourceVisualBeatId)).toEqual(f.timeline.clips.map(c=>c.sourceVisualBeatId));});
 it("preserves exact dialogue",()=>{const f=buildValidEpisodeTimeline();for(const cue of f.episodeTimeline.scenes[0].clips.flatMap(c=>c.dialogueCues)){const b=f.script.blocks.find(x=>x.id===cue.scriptBlockId);if(b?.type==="DIALOGUE")expect(cue.text).toBe(b.text);}});
 it("converts dialogue offsets to Episode-global time",()=>{const f=buildValidEpisodeTimeline();for(const clip of f.episodeTimeline.scenes[0].clips)for(const cue of clip.dialogueCues)expect(cue.startSeconds).toBeGreaterThanOrEqual(clip.startSeconds);});
 it("preserves CUT transition",()=>{const f=buildReadyEpisodeSources();f.timeline.clips[0].transitionIn="CUT";const t=compileEpisodeTimeline({assemblyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",seriesId:f.motionPlan.seriesId,episodeKey:"episodeOne",version:1,scenes:[{order:0,motionPlanStatus:"READY",series:f.series,scene:f.scene,script:f.script,visualPlan:f.visualPlan,storyboard:f.storyboard,animatic:f.timeline,motionPlan:f.motionPlan}]});expect(t.scenes[0].clips[0].transitionIn).toBe("CUT");expect(t.scenes[0].clips[0].transitionDurationSeconds).toBe(0);});
 it("preserves DISSOLVE with bounded visual duration",()=>{const f=buildReadyEpisodeSources();f.timeline.clips[0].transitionIn="DISSOLVE";const t=compileEpisodeTimeline({assemblyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",seriesId:f.motionPlan.seriesId,episodeKey:"episodeOne",version:1,scenes:[{order:0,motionPlanStatus:"READY",series:f.series,scene:f.scene,script:f.script,visualPlan:f.visualPlan,storyboard:f.storyboard,animatic:f.timeline,motionPlan:f.motionPlan}]});expect(t.scenes[0].clips[0].transitionDurationSeconds).toBe(.35);});
 it("preserves HOLD transition",()=>{const f=buildReadyEpisodeSources();f.timeline.clips[0].transitionIn="HOLD";const t=compileEpisodeTimeline({assemblyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",seriesId:f.motionPlan.seriesId,episodeKey:"episodeOne",version:1,scenes:[{order:0,motionPlanStatus:"READY",series:f.series,scene:f.scene,script:f.script,visualPlan:f.visualPlan,storyboard:f.storyboard,animatic:f.timeline,motionPlan:f.motionPlan}]});expect(t.scenes[0].clips[0].transitionIn).toBe("HOLD");});
 it("supports explicit future multi-scene ordering",()=>{const a=buildReadyEpisodeSources(),b=buildReadyEpisodeSources();b.motionPlan.sceneId="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";b.motionPlan.id="cccccccc-cccc-4ccc-8ccc-cccccccccccc";b.motionPlan.animaticId="dddddddd-dddd-4ddd-8ddd-dddddddddddd";b.timeline.sceneId=b.motionPlan.sceneId;b.timeline.id=b.motionPlan.animaticId;const t=compileEpisodeTimeline({assemblyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",seriesId:a.motionPlan.seriesId,episodeKey:"episodeOne",version:1,scenes:[{order:1,motionPlanStatus:"READY",series:b.series,scene:b.scene,script:b.script,visualPlan:b.visualPlan,storyboard:b.storyboard,animatic:b.timeline,motionPlan:b.motionPlan},{order:0,motionPlanStatus:"READY",series:a.series,scene:a.scene,script:a.script,visualPlan:a.visualPlan,storyboard:a.storyboard,animatic:a.timeline,motionPlan:a.motionPlan}]});expect(t.scenes.map(s=>s.order)).toEqual([0,1]);expect(t.scenes[1].startSeconds).toBe(t.scenes[0].durationSeconds);});
 it("rejects duplicate Scene IDs",()=>{const f=buildReadyEpisodeSources();expect(()=>compileEpisodeTimeline({assemblyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",seriesId:f.motionPlan.seriesId,episodeKey:"episodeOne",version:1,scenes:[0,1].map(order=>({order,motionPlanStatus:"READY" as const,series:f.series,scene:f.scene,script:f.script,visualPlan:f.visualPlan,storyboard:f.storyboard,animatic:f.timeline,motionPlan:f.motionPlan}))})).toThrow();});
 it("rejects unresolved clips",()=>{const f=buildReadyEpisodeSources();f.motionPlan.clips[0].generationStatus="PENDING";f.motionPlan.clips[0].outputAsset=null;expect(()=>compileEpisodeTimeline({assemblyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",seriesId:f.motionPlan.seriesId,episodeKey:"episodeOne",version:1,scenes:[{order:0,motionPlanStatus:"READY",series:f.series,scene:f.scene,script:f.script,visualPlan:f.visualPlan,storyboard:f.storyboard,animatic:f.timeline,motionPlan:f.motionPlan}]})).toThrow();});
 it("reports complete visual and Script coverage",()=>{const t=compile();expect(t.validation.hasVisualCoverage).toBe(true);expect(t.validation.hasScriptCoverage).toBe(true);});
 it("does not mutate parent objects or canon",()=>{const f=buildReadyEpisodeSources();const before=[JSON.stringify(f.series),JSON.stringify(f.scene),JSON.stringify(f.script),JSON.stringify(f.visualPlan),JSON.stringify(f.storyboard),JSON.stringify(f.timeline),JSON.stringify(f.motionPlan),JSON.stringify(f.series.canon)];compileEpisodeTimeline({assemblyId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",seriesId:f.motionPlan.seriesId,episodeKey:"episodeOne",version:1,scenes:[{order:0,motionPlanStatus:"READY",series:f.series,scene:f.scene,script:f.script,visualPlan:f.visualPlan,storyboard:f.storyboard,animatic:f.timeline,motionPlan:f.motionPlan}]});expect([JSON.stringify(f.series),JSON.stringify(f.scene),JSON.stringify(f.script),JSON.stringify(f.visualPlan),JSON.stringify(f.storyboard),JSON.stringify(f.timeline),JSON.stringify(f.motionPlan),JSON.stringify(f.series.canon)]).toEqual(before);});
 it("contains no audio or prompt/provider fields",()=>{const s=JSON.stringify(compile());expect(s).not.toContain("audio");expect(s).not.toContain("promptChecksum");expect(s).not.toContain("providerTask");});
});
